#!/bin/bash

PID=$(cat /tmp/tobobrowse.pid > /dev/null 2&>1 || echo '')
if [ -n "$PID" ]; then
  (kill $PID && echo "Restarting server...") || echo "Starting server..."
else
  echo "Starting server..."
fi
python tobobrowse_daemon.py
